Repository OCA/oca-github-bot, pull requests merged in 2020-03, with the labels that each got.

#76 Add merging label while merging a PR
  src/oca_github_bot/tasks/merge_bot.py
Labels: Bot Task, enhancement

#107 [IMP] make APPROVALS_REQUIRED configurable
  environment.sample
  newsfragments/107.feature
  src/oca_github_bot/config.py
  src/oca_github_bot/tasks/tag_approved.py
  src/oca_github_bot/tasks/tag_ready_to_merge.py
Labels: needs review

#111 Imp make dynamic GitHub ignored
  environment.sample
  newsfragments/111.feature
  src/oca_github_bot/config.py
Labels: needs review

#112 Add bot tasks disabled
  README.rst
  environment.sample
  newsfragments/112.feature
  src/oca_github_bot/config.py
  tests/test_switchable.py
Labels: approved
